/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_cientifica;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.script.*;
import javax.swing.JOptionPane;


/**
 *
 * @author GERSON
 */
public class Calculadora extends javax.swing.JFrame {

    private boolean deg = true;
    
    private Integer layoutX;
    private Integer layoutY;

    private Color colorSeleccionado = new Color(29, 32, 36);
    private Color colorNormal = new Color(52, 58, 65);
    private ScriptEngine engine = new ScriptEngineManager(null).getEngineByName("ECMAScript");
    private String memoria = "";
    private String mostrar = "";
    private String temp = "";
    public Calculadora() {
         try {
             UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
             SwingUtilities.updateComponentTreeUI(this);
         } catch (Exception ex){}
         initComponents();
         lblVisor.setText("0");
         lblEntrada.setText("0");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumericoBasico = new javax.swing.JPanel();
        btnDel = new javax.swing.JButton();
        bntBor = new javax.swing.JButton();
        btnMasMenos = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn_N7 = new javax.swing.JButton();
        btn_N8 = new javax.swing.JButton();
        btn_N9 = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btn_N4 = new javax.swing.JButton();
        btn_N5 = new javax.swing.JButton();
        btn_N6 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btn_N1 = new javax.swing.JButton();
        btn_N2 = new javax.swing.JButton();
        btn_N3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btn_N0 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnValAbs = new javax.swing.JButton();
        panelExtra = new javax.swing.JPanel();
        btnDeg = new javax.swing.JButton();
        btnRad = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        btnParentesis1 = new javax.swing.JButton();
        btnParentesis2 = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        panelVisor = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        lblVisor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teclaPresionada(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNumericoBasico.setLayout(new java.awt.GridLayout(5, 4));

        btnDel.setBackground(new java.awt.Color(55, 67, 82));
        btnDel.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnDel.setText("CE");
        btnDel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnDel.setFocusable(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnDel);

        bntBor.setBackground(new java.awt.Color(55, 67, 82));
        bntBor.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        bntBor.setText("C");
        bntBor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        bntBor.setFocusable(false);
        bntBor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBorActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(bntBor);

        btnMasMenos.setBackground(new java.awt.Color(55, 67, 82));
        btnMasMenos.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnMasMenos.setText("±");
        btnMasMenos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnMasMenos.setFocusable(false);
        btnMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasMenosActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnMasMenos);

        btnDiv.setBackground(new java.awt.Color(55, 67, 82));
        btnDiv.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnDiv.setText("÷");
        btnDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnDiv.setFocusable(false);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnDiv);

        btn_N7.setBackground(new java.awt.Color(91, 106, 124));
        btn_N7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N7.setText("7");
        btn_N7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N7.setFocusable(false);
        btn_N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N7ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N7);

        btn_N8.setBackground(new java.awt.Color(91, 106, 124));
        btn_N8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N8.setText("8");
        btn_N8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N8.setFocusable(false);
        btn_N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N8ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N8);

        btn_N9.setBackground(new java.awt.Color(91, 106, 124));
        btn_N9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N9.setText("9");
        btn_N9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N9.setFocusable(false);
        btn_N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N9ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N9);

        btnMult.setBackground(new java.awt.Color(55, 67, 82));
        btnMult.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnMult.setText("×");
        btnMult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnMult.setFocusable(false);
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnMult);

        btn_N4.setBackground(new java.awt.Color(91, 106, 124));
        btn_N4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N4.setText("4");
        btn_N4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N4.setFocusable(false);
        btn_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N4ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N4);

        btn_N5.setBackground(new java.awt.Color(91, 106, 124));
        btn_N5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N5.setText("5");
        btn_N5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N5.setFocusable(false);
        btn_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N5ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N5);

        btn_N6.setBackground(new java.awt.Color(91, 106, 124));
        btn_N6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N6.setText("6");
        btn_N6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N6.setFocusable(false);
        btn_N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N6ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N6);

        btnResta.setBackground(new java.awt.Color(55, 67, 82));
        btnResta.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnResta.setText("-");
        btnResta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnResta.setFocusable(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnResta);

        btn_N1.setBackground(new java.awt.Color(91, 106, 124));
        btn_N1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N1.setText("1");
        btn_N1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N1.setFocusable(false);
        btn_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N1ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N1);

        btn_N2.setBackground(new java.awt.Color(91, 106, 124));
        btn_N2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N2.setText("2");
        btn_N2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N2.setFocusable(false);
        btn_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N2ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N2);

        btn_N3.setBackground(new java.awt.Color(91, 106, 124));
        btn_N3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N3.setText("3");
        btn_N3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N3.setFocusable(false);
        btn_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N3ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N3);

        btnSuma.setBackground(new java.awt.Color(55, 67, 82));
        btnSuma.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnSuma.setText("+");
        btnSuma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnSuma.setFocusable(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnSuma);

        btnPunto.setBackground(new java.awt.Color(55, 67, 82));
        btnPunto.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnPunto.setFocusable(false);
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnPunto);

        btn_N0.setBackground(new java.awt.Color(91, 106, 124));
        btn_N0.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btn_N0.setText("0");
        btn_N0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btn_N0.setFocusable(false);
        btn_N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_N0ActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btn_N0);

        btnIgual.setBackground(new java.awt.Color(31, 64, 105));
        btnIgual.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnIgual.setFocusable(false);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnIgual);

        btnValAbs.setBackground(new java.awt.Color(55, 67, 82));
        btnValAbs.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        btnValAbs.setText("|x|");
        btnValAbs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnValAbs.setFocusable(false);
        btnValAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValAbsActionPerformed(evt);
            }
        });
        panelNumericoBasico.add(btnValAbs);

        getContentPane().add(panelNumericoBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 600, 320));

        panelExtra.setLayout(new java.awt.GridLayout(5, 3));

        btnDeg.setBackground(new java.awt.Color(29, 32, 36));
        btnDeg.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnDeg.setText("Deg");
        btnDeg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnDeg.setFocusable(false);
        btnDeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegActionPerformed(evt);
            }
        });
        panelExtra.add(btnDeg);

        btnRad.setBackground(new java.awt.Color(52, 58, 65));
        btnRad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnRad.setText("Rad");
        btnRad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnRad.setFocusable(false);
        btnRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadActionPerformed(evt);
            }
        });
        panelExtra.add(btnRad);

        btnPi.setBackground(new java.awt.Color(52, 58, 65));
        btnPi.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnPi.setText("<html>&pi</html>");
        btnPi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnPi.setFocusable(false);
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });
        panelExtra.add(btnPi);

        btnSin.setBackground(new java.awt.Color(52, 58, 65));
        btnSin.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnSin.setText("Sin");
        btnSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnSin.setFocusable(false);
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        panelExtra.add(btnSin);

        btnCos.setBackground(new java.awt.Color(52, 58, 65));
        btnCos.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCos.setText("Cos");
        btnCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnCos.setFocusable(false);
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        panelExtra.add(btnCos);

        btnTan.setBackground(new java.awt.Color(52, 58, 65));
        btnTan.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnTan.setText("Tan");
        btnTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnTan.setFocusable(false);
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        panelExtra.add(btnTan);

        btnE.setBackground(new java.awt.Color(52, 58, 65));
        btnE.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnE.setText("e");
        btnE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnE.setFocusable(false);
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        panelExtra.add(btnE);

        btnLn.setBackground(new java.awt.Color(52, 58, 65));
        btnLn.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnLn.setText("Ln");
        btnLn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnLn.setFocusable(false);
        btnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLnActionPerformed(evt);
            }
        });
        panelExtra.add(btnLn);

        btnLog.setBackground(new java.awt.Color(52, 58, 65));
        btnLog.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnLog.setText("Log");
        btnLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnLog.setFocusable(false);
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        panelExtra.add(btnLog);

        btnPotencia.setBackground(new java.awt.Color(52, 58, 65));
        btnPotencia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnPotencia.setText("10^x");
        btnPotencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnPotencia.setFocusable(false);
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });
        panelExtra.add(btnPotencia);

        btnCuadrado.setBackground(new java.awt.Color(52, 58, 65));
        btnCuadrado.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCuadrado.setText("<html>x&sup2</html>");
        btnCuadrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnCuadrado.setFocusable(false);
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });
        panelExtra.add(btnCuadrado);

        jButton26.setBackground(new java.awt.Color(52, 58, 65));
        jButton26.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton26.setText("<html>x&sup3</html>");
        jButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        jButton26.setFocusable(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        panelExtra.add(jButton26);

        btnParentesis1.setBackground(new java.awt.Color(52, 58, 65));
        btnParentesis1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnParentesis1.setText("(");
        btnParentesis1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnParentesis1.setFocusable(false);
        btnParentesis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesis1ActionPerformed(evt);
            }
        });
        panelExtra.add(btnParentesis1);

        btnParentesis2.setBackground(new java.awt.Color(52, 58, 65));
        btnParentesis2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnParentesis2.setText(")");
        btnParentesis2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnParentesis2.setFocusable(false);
        btnParentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesis2ActionPerformed(evt);
            }
        });
        panelExtra.add(btnParentesis2);

        btnFact.setBackground(new java.awt.Color(52, 58, 65));
        btnFact.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnFact.setText("n!");
        btnFact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 126, 145)));
        btnFact.setFocusable(false);
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });
        panelExtra.add(btnFact);

        getContentPane().add(panelExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 300, 320));

        panelTitulo.setBackground(new java.awt.Color(55, 67, 82));
        panelTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelTituloMouseDragged(evt);
            }
        });
        panelTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTituloMousePressed(evt);
            }
        });
        panelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        titulo.setText("Calculadora Científica");
        panelTitulo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 430, 50));

        btnCerrar.setBackground(new java.awt.Color(53, 62, 73));
        btnCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnCerrar.setText("<html>&times</html>");
        btnCerrar.setBorder(null);
        btnCerrar.setFocusable(false);
        btnCerrar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarMouseExited(evt);
            }
        });
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelTitulo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        btnMin.setBackground(new java.awt.Color(53, 62, 73));
        btnMin.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnMin.setText("_");
        btnMin.setBorder(null);
        btnMin.setFocusable(false);
        btnMin.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        panelTitulo.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, 50));

        btnHelp.setBackground(new java.awt.Color(53, 62, 73));
        btnHelp.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnHelp.setMnemonic(112);
        btnHelp.setText("?");
        btnHelp.setBorder(null);
        btnHelp.setFocusable(false);
        btnHelp.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        panelTitulo.add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 50));

        getContentPane().add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        panelVisor.setBackground(new java.awt.Color(81, 92, 105));
        panelVisor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEntrada.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntrada.setText("131243");
        panelVisor.add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 150));

        lblVisor.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVisor.setText("<html>12 &times 3</html>");
        panelVisor.add(lblVisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 70));

        getContentPane().add(panelVisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N7ActionPerformed
        addMemory(btn_N7.getText());
    }//GEN-LAST:event_btn_N7ActionPerformed

    private void btn_N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N8ActionPerformed
        addMemory(btn_N8.getText());
    }//GEN-LAST:event_btn_N8ActionPerformed

    private void btn_N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N9ActionPerformed
        addMemory(btn_N9.getText());
    }//GEN-LAST:event_btn_N9ActionPerformed

    private void btn_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N4ActionPerformed
        addMemory(btn_N4.getText());
    }//GEN-LAST:event_btn_N4ActionPerformed

    private void btn_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N5ActionPerformed
        addMemory(btn_N5.getText());
    }//GEN-LAST:event_btn_N5ActionPerformed

    private void btn_N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N6ActionPerformed
        addMemory(btn_N6.getText());
    }//GEN-LAST:event_btn_N6ActionPerformed

    private void btn_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N1ActionPerformed
        addMemory(btn_N1.getText());
    }//GEN-LAST:event_btn_N1ActionPerformed

    private void btn_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N2ActionPerformed
        addMemory(btn_N2.getText());
    }//GEN-LAST:event_btn_N2ActionPerformed

    private void btn_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N3ActionPerformed
        addMemory(btn_N3.getText());
    }//GEN-LAST:event_btn_N3ActionPerformed

    private void btn_N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_N0ActionPerformed
        addMemory(btn_N0.getText());
    }//GEN-LAST:event_btn_N0ActionPerformed

    private void bntBorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBorActionPerformed
        if(temp.length() > 0){
            temp = temp.substring(0, temp.length()-1);
            lblVisor.setText(mostrar);
            try {
                lblVisor.setText(mostrar + temp);
                if(temp.length() > 0) lblEntrada.setText(engine.eval(memoria + temp).toString());
                else lblEntrada.setText("");
            } catch (ScriptException ex) {}
        }
    }//GEN-LAST:event_bntBorActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        lblEntrada.setText("");
        lblVisor.setText("");
        memoria = "";
        mostrar = "";
        temp = "";
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if(!temp.contains(".")){
            if(temp.length() == 0){
                temp = "0" + btnPunto.getText();
                lblVisor.setText(mostrar + temp);
            }else{
                temp += btnPunto.getText();
                lblVisor.setText(mostrar + temp);
                System.out.println("tiene un numero al ultimo");
            }
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasMenosActionPerformed
        if(temp.length() > 0){
            if(temp.contains("-")){
                temp = temp.substring(1);
                lblVisor.setText(mostrar + temp);
            }else{
                temp = "-" + temp;
                lblVisor.setText(mostrar + temp);
            }
        }
    }//GEN-LAST:event_btnMasMenosActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        addMemory("/", btnDiv.getText());
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnParentesis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesis1ActionPerformed
        addMemory(btnParentesis1.getText(), true);
    }//GEN-LAST:event_btnParentesis1ActionPerformed

    private void btnParentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesis2ActionPerformed
        addMemory(btnParentesis2.getText(), false);
    }//GEN-LAST:event_btnParentesis2ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        try{
            addMemory("", "");
            lblVisor.setText(mostrar);
            lblEntrada.setText(engine.eval(memoria).toString());
        } catch (ScriptException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Ha ocurido un error :(", "Error", JOptionPane.ERROR_MESSAGE);
            lblEntrada.setText("ERROR");
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        try{
            funcionEspecial(String.valueOf( fact(Double.parseDouble(engine.eval(temp).toString())) ));
        }catch(Exception e){}
    }//GEN-LAST:event_btnFactActionPerformed

    private double fact(double a){
        if(a == 1) return a;
        else return fact(a - 1)* a;
    }
    
    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        addMemory("*", "×");
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        addMemory("-", "−");
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        addMemory("+", "+");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnDegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegActionPerformed
        toggleGrados();
    }//GEN-LAST:event_btnDegActionPerformed

    private void btnRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadActionPerformed
        toggleGrados();
    }//GEN-LAST:event_btnRadActionPerformed

    private void btnValAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValAbsActionPerformed
        try{
            funcionEspecial(String.valueOf(Math.abs(Double.parseDouble(engine.eval(temp).toString()))));
        }catch(Exception e){}
    }//GEN-LAST:event_btnValAbsActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        if(temp.isEmpty()){
            temp = String.valueOf(Math.PI);
        }
        actualizarVistaSinError();
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        if(temp.isEmpty()){
            temp = String.valueOf(Math.E);
        }
        actualizarVistaSinError();
    }//GEN-LAST:event_btnEActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        try{
            Double _angulo = Double.parseDouble(engine.eval(temp).toString());
            if(deg) _angulo = Math.toRadians(_angulo);
            funcionEspecial(String.valueOf((double)Math.round(Math.sin( Double.parseDouble(engine.eval(_angulo.toString()).toString()))*Math.pow(10, 15))/Math.pow(10, 15)));
        }catch(Exception e){}
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        try{
            Double _angulo = Double.parseDouble(engine.eval(temp).toString());
            if(deg) _angulo = Math.toRadians(_angulo);
            funcionEspecial(String.valueOf((double)Math.round(Math.cos(Double.parseDouble(engine.eval(_angulo.toString()).toString()))*Math.pow(10, 15))/Math.pow(10, 15)));
        }catch(Exception e){}
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        try{
            Double _angulo = Double.parseDouble(engine.eval(temp).toString());
            if(deg) _angulo = Math.toRadians(_angulo);      
            funcionEspecial(String.valueOf((double)Math.round(Math.tan(Double.parseDouble(engine.eval(_angulo.toString()).toString()))*Math.pow(10, 15))/Math.pow(10, 15)));
        }catch(Exception e){}
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLnActionPerformed
        try{
            funcionEspecial(String.valueOf( Math.log( Double.parseDouble(engine.eval(temp).toString()) ) ));
        }catch(Exception e){}
    }//GEN-LAST:event_btnLnActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        try{
            funcionEspecial(String.valueOf( Math.log10(Double.parseDouble(engine.eval(temp).toString()) ) ));
        }catch(Exception e){}
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        try{
            funcionEspecial(String.valueOf( Math.pow(10, Double.parseDouble(engine.eval(temp).toString()) ) ));
        }catch(Exception e){}
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        try{
            funcionEspecial(String.valueOf( Math.pow(Double.parseDouble(engine.eval(temp).toString()), 2) ));
        }catch(Exception e){}
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        try{
            funcionEspecial(String.valueOf( Math.pow(Double.parseDouble(engine.eval(temp).toString()), 3) ));
        }catch(Exception e){}
    }//GEN-LAST:event_jButton26ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed

    private void panelTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloMouseDragged
        this.setLocation(evt.getXOnScreen() - layoutX, evt.getYOnScreen() - layoutY);
    }//GEN-LAST:event_panelTituloMouseDragged

    private void panelTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTituloMousePressed
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1){
            layoutX = evt.getX();
            layoutY = evt.getY();
        }
    }//GEN-LAST:event_panelTituloMousePressed

    private void teclaPresionada(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teclaPresionada
        char input = evt.getKeyChar();
        switch(input){
            case '0':
                btn_N0.doClick();
                break;
            case '1':
                btn_N1.doClick();
                break;
            case '2':
                btn_N2.doClick();
                break;
            case '3':
                btn_N3.doClick();
                break;
            case '4':
                btn_N4.doClick();
                break;
            case '5':
                btn_N5.doClick();
                break;
            case '6':
                btn_N6.doClick();
                break;
            case '7':
                btn_N7.doClick();
                break;
            case '8':
                btn_N8.doClick();
                break;
            case '9':
                btn_N9.doClick();
                break;
            case '-':
                btnResta.doClick();
                break;
            case '+':
                btnSuma.doClick();
                break;
            case '*':
                btnMult.doClick();
                break;
            case '/':
                btnDiv.doClick();
                break;
            case '.':
                btnPunto.doClick();
                break;
            case '(':
                btnParentesis1.doClick();
                break;
            case ')':
                btnParentesis2.doClick();
                break;
            case '!':
                btnFact.doClick();
                break;
            case 's':
            case 'S':
                btnSin.doClick();
                break;
            case 'c':
            case 'C':
                btnCos.doClick();
                break;
            case 't':
            case 'T':
                btnTan.doClick();
                break;
            case 'r':
            case 'R':
                btnRad.doClick();
                break;
            case 'd':
            case 'D':
                btnDeg.doClick();
                break;
            case 'p':
            case 'P':
                btnPi.doClick();
                break;
            case 'e':
            case 'E':
                btnE.doClick();
                break;
            case '^':
                btnPotencia.doClick();
                break;
            case 8:
                bntBor.doClick();
                break;
            case 27:
                btnDel.doClick();
                break;
        }
    }//GEN-LAST:event_teclaPresionada

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        JOptionPane.showMessageDialog(rootPane, "<html>Autor: <b>nothyG</b>\nUsa los atajos del teclado con las iniciales de los botones y teclado numérico\n ESC para borrar todo\n DEL para borrar caracteres", "Acerca de la calculadora", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseEntered
        btnCerrar.setBackground(new Color(200, 20, 20));
    }//GEN-LAST:event_btnCerrarMouseEntered

    private void btnCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseExited
        btnCerrar.setBackground(new Color(53, 62, 73));
    }//GEN-LAST:event_btnCerrarMouseExited

    private void toggleGrados(){
        deg = !deg;
        if(deg){
            btnRad.setBackground(colorNormal);
            btnDeg.setBackground(colorSeleccionado);
        }else{
            btnRad.setBackground(colorSeleccionado);
            btnDeg.setBackground(colorNormal);
        }
    }
    
    private void funcionEspecial(String value){
        if(!temp.isEmpty()){
            temp = value;
        }
        actualizarVistaSinError();
    }
    
    private void addMemory(String s, boolean flag){
        memoria += temp + s;
        mostrar += temp + s;
        temp = "";
        lblVisor.setText(mostrar);
        try {
            lblEntrada.setText(engine.eval(memoria).toString());
        } catch (ScriptException ex) {}
        if(!flag){
            for(int i = memoria.length() - 1; i >= 0; i--) {
                if(memoria.substring(i).matches("\\(([^()]*[^()]*)\\)")){
                    temp = memoria.substring(i);
                    String a = mostrar.substring(i);
                    memoria = memoria.substring(0, memoria.indexOf(temp));
                    mostrar = mostrar.substring(0, mostrar.indexOf(a));
                }
            }
        }
    }
    
    private void addMemory(String s, String a){
        if(!temp.isEmpty()){
            memoria += temp + s;
            mostrar += temp + a;
            temp = "";
            lblVisor.setText(mostrar);
            lblEntrada.setText("");
        }
    }
    
    private void addMemory(String s){
        temp += s;
        lblVisor.setText(mostrar + temp);
        actualizarVistaSinError();
    }
    
    private void actualizarVistaSinError(){
        try {
            lblVisor.setText(mostrar + temp);
            lblEntrada.setText(engine.eval(memoria + temp).toString());
        } catch (ScriptException ex) {}
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBor;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnDeg;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMasMenos;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnParentesis1;
    private javax.swing.JButton btnParentesis2;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRad;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnValAbs;
    private javax.swing.JButton btn_N0;
    private javax.swing.JButton btn_N1;
    private javax.swing.JButton btn_N2;
    private javax.swing.JButton btn_N3;
    private javax.swing.JButton btn_N4;
    private javax.swing.JButton btn_N5;
    private javax.swing.JButton btn_N6;
    private javax.swing.JButton btn_N7;
    private javax.swing.JButton btn_N8;
    private javax.swing.JButton btn_N9;
    private javax.swing.JButton jButton26;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblVisor;
    private javax.swing.JPanel panelExtra;
    private javax.swing.JPanel panelNumericoBasico;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelVisor;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
